%YAML:1.0
#In our experiment, we normally use two images that id's difference is 5 to compare
image0_id: '0030'
image1_id: '0035'
image0_type: rgb
image1_type: rgb

use_groundtruth: '1'

dataset: eth_cvg

im_address: /home/zhaozhong/dataset/ethz_cvg/ethl_syn1_global/ethl1_global/

depth_factor: 5000.0

fx: 481.20
fy: -480.0
cx: 319.50
cy: 239.50
